name: Python Application CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy-demo-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run application
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Run tests
      run: pytest tests

    - name: Configure AWS credentials
      if: success() && steps.run_tests.outcome == 'success'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Login to Amazon ECR
      if: success() && steps.run_tests.outcome == 'success'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      if: success() && steps.run_tests.outcome == 'success'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: your-ecr-repo-name  # Replace with your ECR repository name
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG